/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContentObjectType = ("STRING" | "FILE" | "FOLDER")
export type CmsValueDataObject =
  | CmsStringDataObject
  | CmsFileDataObject
  | CmsDataFileDataObject
  | CmsReadFileDataObject;
export type CmsDataObject = CmsFolderDataObject | CmsValueDataObject;

export interface CMS {
  cmsAddLocalesArgs: CmsAddLocalesArgs;
  cmsCountLocaleValuesArgs: CmsCountLocaleValuesArgs;
  cmsCreateFileArgs: CmsCreateFileArgs;
  cmsCreateStringArgs: CmsCreateStringArgs;
  cmsData: CmsData;
  cmsDataArgs: CmsDataArgs;
  cmsDataObject: CmsDataObject;
  cmsDeleteArgs: CmsDeleteArgs;
  cmsDeleteValueArgs: CmsDeleteValueArgs;
  cmsEditorDataContext: CmsEditorDataContext;
  cmsInitializeResult: CmsInitializeResult;
  cmsReadArgs: CmsReadArgs;
  cmsRemoveLocalesArgs: CmsRemoveLocalesArgs;
  cmsTranslationArgs: CmsTranslationArgs;
  cmsTranslationResponse: CmsTranslationResponse[];
  cmsUpdateValuesArgs: CmsUpdateValuesArgs;
  long: MapStringLong;
  string: string[];
  void: Void;
  [k: string]: unknown;
}
export interface CmsAddLocalesArgs {
  context: CmsEditorDataContext;
  locales: string[];
}
export interface CmsEditorDataContext {
  app: string;
  file: string;
  pmv: string;
}
export interface CmsCountLocaleValuesArgs {
  context: CmsEditorDataContext;
  locales: string[];
}
export interface CmsCreateFileArgs {
  contentObject: CmsFileDataObject;
  context: CmsEditorDataContext;
}
export interface CmsFileDataObject {
  fileExtension: string;
  type: ContentObjectType;
  uri: string;
  values: MapStringString;
}
export interface MapStringString {
  [k: string]: string;
}
export interface CmsCreateStringArgs {
  contentObject: CmsStringDataObject;
  context: CmsEditorDataContext;
}
export interface CmsStringDataObject {
  type: ContentObjectType;
  uri: string;
  values: MapStringString;
}
export interface CmsData {
  context: CmsEditorDataContext;
  data: (CmsFolderDataObject | CmsValueDataObject)[];
  helpUrl: string;
}
export interface CmsFolderDataObject {
  type: ContentObjectType;
  uri: string;
}
export interface CmsDataFileDataObject {
  fileExtension: string;
  mimeType: string;
  type: ContentObjectType;
  uri: string;
  values: MapStringBoolean;
}
export interface MapStringBoolean {
  [k: string]: boolean;
}
export interface CmsReadFileDataObject {
  fileExtension: string;
  mimeType: string;
  type: ContentObjectType;
  uri: string;
  values: MapStringURI;
}
export interface MapStringURI {
  [k: string]: string;
}
export interface CmsDataArgs {
  context: CmsEditorDataContext;
  languageTags: string[];
}
export interface CmsDeleteArgs {
  context: CmsEditorDataContext;
  uris: string[];
}
export interface CmsDeleteValueArgs {
  context: CmsEditorDataContext;
  deleteRequest: CmsDeleteValueRequest;
}
export interface CmsDeleteValueRequest {
  languageTag: string;
  uri: string;
}
export interface CmsInitializeResult {
  capabilities: Capabilities;
}
export interface Capabilities {
  translationServiceEnabled: boolean;
}
export interface CmsReadArgs {
  context: CmsEditorDataContext;
  uri: string;
}
export interface CmsRemoveLocalesArgs {
  context: CmsEditorDataContext;
  locales: string[];
}
export interface CmsTranslationArgs {
  context: CmsEditorDataContext;
  translationRequest: CmsTranslationRequest;
}
export interface CmsTranslationRequest {
  sourceLanguageTag: string;
  targetLanguageTags: string[];
  uris: string[];
}
export interface CmsTranslationResponse {
  uri: string;
  values: MapStringTranslatedValue;
}
export interface MapStringTranslatedValue {
  [k: string]: TranslatedValue;
}
export interface TranslatedValue {
  original: string;
  translation: string;
}
export interface CmsUpdateValuesArgs {
  context: CmsEditorDataContext;
  updateRequests: CmsUpdateValuesRequest[];
}
export interface CmsUpdateValuesRequest {
  uri: string;
  values: MapStringString;
}
export interface MapStringLong {
  [k: string]: number;
}
export interface Void {}
