/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContentObjectType = ("STRING" | "FILE" | "FOLDER")
export type CmsDataObject = CmsFolderDataObject | CmsStringDataObject | CmsFileDataObject;

export interface CMS {
  cmsActionArgs: CmsActionArgs;
  cmsAddLocalesArgs: CmsAddLocalesArgs;
  cmsCountLocaleValuesArgs: CmsCountLocaleValuesArgs;
  cmsCreateFileArgs: CmsCreateFileArgs;
  cmsCreateStringArgs: CmsCreateStringArgs;
  cmsData: CmsData;
  cmsDataArgs: CmsDataArgs;
  cmsDataObject: CmsDataObject;
  cmsDeleteArgs: CmsDeleteArgs;
  cmsDeleteValueArgs: CmsDeleteValueArgs;
  cmsEditorDataContext: CmsEditorDataContext;
  cmsReadArgs: CmsReadArgs;
  cmsRemoveLocalesArgs: CmsRemoveLocalesArgs;
  cmsUpdateFileValueArgs: CmsUpdateFileValueArgs;
  cmsUpdateStringValueArgs: CmsUpdateStringValueArgs;
  long: MapStringLong;
  string: string[];
  void: Void;
  [k: string]: unknown;
}
export interface CmsActionArgs {
  actionId: "openUrl";
  context: CmsEditorDataContext;
  payload: string;
}
export interface CmsEditorDataContext {
  app: string;
  file: string;
  pmv: string;
}
export interface CmsAddLocalesArgs {
  context: CmsEditorDataContext;
  locales: string[];
}
export interface CmsCountLocaleValuesArgs {
  context: CmsEditorDataContext;
  locales: string[];
}
export interface CmsCreateFileArgs {
  contentObject: CmsFileDataObject;
  context: CmsEditorDataContext;
}
export interface CmsFileDataObject {
  fileExtension: string;
  type: ContentObjectType;
  uri: string;
  values: MapStringByte;
}
export interface MapStringByte {
  [k: string]: Array<number>;
}
export interface CmsCreateStringArgs {
  contentObject: CmsStringDataObject;
  context: CmsEditorDataContext;
}
export interface CmsStringDataObject {
  type: ContentObjectType;
  uri: string;
  values: MapStringString;
}
export interface MapStringString {
  [k: string]: string;
}
export interface CmsData {
  context: CmsEditorDataContext;
  data: (CmsFolderDataObject | CmsStringDataObject | CmsFileDataObject)[];
  helpUrl: string;
}
export interface CmsFolderDataObject {
  type: ContentObjectType;
  uri: string;
}
export interface CmsDataArgs {
  context: CmsEditorDataContext;
  languageTags: string[];
}
export interface CmsDeleteArgs {
  context: CmsEditorDataContext;
  uri: string;
}
export interface CmsDeleteValueArgs {
  context: CmsEditorDataContext;
  deleteObject: CmsDeleteValueObject;
}
export interface CmsDeleteValueObject {
  languageTag: string;
  uri: string;
}
export interface CmsReadArgs {
  context: CmsEditorDataContext;
  uri: string;
}
export interface CmsRemoveLocalesArgs {
  context: CmsEditorDataContext;
  locales: string[];
}
export interface CmsUpdateFileValueArgs {
  context: CmsEditorDataContext;
  updateObject: CmsUpdateFileValueObject;
}
export interface CmsUpdateFileValueObject {
  languageTag: string;
  uri: string;
  value: Array<number>;
}
export interface CmsUpdateStringValueArgs {
  context: CmsEditorDataContext;
  updateObject: CmsUpdateStringValueObject;
}
export interface CmsUpdateStringValueObject {
  languageTag: string;
  uri: string;
  value: string;
}
export interface MapStringLong {
  [k: string]: number;
}
export interface Void {}
